version: "3.6"
x-env-aliases:
  &DEFAULT_BUILD_ARGS
    PHP_TAG: "${PHP_VERSION:-7.3}-cli-alpine${ALPINE_VERSION:-3.10}"
    PHP_API_VERSION: "${PHP_API_VERSION:-20180731}"
    COMPOSER_ARGS: "${COMPOSER_ARGS:-install}"
    SWOOLE_VERSION: "${SWOOLE_VERSION:-4.3.6}"

volumes:
  mariadb_data_volume: {}

services:
  cli-dev:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-k911}/${IMAGE:-swoole-bundle-cli}:${TAG:-latest}"
    build:
      context: .
      target: CliDev
      args:
        <<: *DEFAULT_BUILD_ARGS
    ports:
      - 9501:9501
      - 9601:9601
    volumes:
      - ".:/usr/src/app:delegated"
    environment:
      - SYMFONY_ENV=dev
      - APP_ENV=dev
      - PORT=9501
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN
    links:
      - swoole-mariadb-dev
    command: ["swoole:server:run", "--api", "--api-port=9601"]

  cli-dev-sdebug:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-k911}/${IMAGE:-swoole-bundle-cli-sdebug}:${TAG:-latest}"
    build:
      context: .
      target: CliDevSdebug
      args:
        <<: *DEFAULT_BUILD_ARGS
    ports:
      - 9502:9501
      - 9602:9601
    volumes:
      - ".:/usr/src/app:delegated"
    environment:
      - SYMFONY_ENV=dev
      - APP_ENV=dev
      - PORT=9501
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN
      - XDEBUG_CONFIG=remote_host=docker.for.mac.host.internal idekey=PHPSTORM
    links:
      - swoole-mariadb-dev
    command: ["swoole:server:run", "--api", "--api-port=9601"]

  cli-dev-coverage:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-k911}/${IMAGE:-swoole-bundle-coverage-xdebug}:${TAG:-latest}"
    build:
      context: .
      target: CoverageXdebug
      args:
        <<: *DEFAULT_BUILD_ARGS
    volumes:
      - ".:/usr/src/app:delegated"
    environment:
      - SYMFONY_ENV=dev
      - APP_ENV=dev
    entrypoint: ["/usr/local/bin/php", "-S", "localhost:8000", "-t", "."]

  # prod environment, debug false - for performance testing
  cli-non-debug-dev:
    image: "${REGISTRY:-docker.io}/${NAMESPACE:-k911}/${IMAGE:-swoole-bundle-cli}:${TAG:-latest}"
    build:
      context: .
      target: CliDev
      args:
        <<: *DEFAULT_BUILD_ARGS
    ports:
      - 9503:9503
      - 9603:9602
    volumes:
      - ".:/usr/src/app:delegated"
    environment:
      - SYMFONY_ENV=prod
      - APP_ENV=prod
      - APP_DEBUG=
      - PORT=9502
    links:
      - swoole-mariadb-dev
    command: ["swoole:server:run", "--api", "--api-port=9602"]

  blackfire:
    image: blackfire/blackfire
    environment:
      # Exposes the host BLACKFIRE_SERVER_ID and TOKEN environment variables.
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN

  # nginx - for performance testing comparison
  app-nginx:
    container_name: app-nginx
    image: nginx:latest
    depends_on:
      - cli-non-debug-dev
    links:
      - cli-non-debug-dev
    ports:
      - 9504:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  # DB
  swoole-mariadb-dev:
    container_name: swoole-mariadb-dev
    image: mariadb:10.3.0
    environment:
      MYSQL_ROOT_PASSWORD: Start@123
      MYSQL_USER: swoole
      MYSQL_PASSWORD: Password1
      MYSQL_DATABASE: swoole
    ports:
      - 33006:3306
    volumes:
      - mariadb_data_volume:/var/lib/mysql
